// frontend-angular/src/app/telas/pessoa/cadastro-pessoa.component.ts
import { Component } from '@angular/core';
import { CadastroBase } from 'src/app/components/cadastro/cadastro-base.component';
import { Entidade } from 'src/app/model/entidade-model'


@Component({
  selector: 'cadastro-pessoa',
  templateUrl: './cadastro-pessoa.component.html',
})
export class CadastroPessoaComponent extends CadastroBase {

  entidade: Entidade = new Entidade("pessoas");

  paises = [
      { id: '1', nome: 'Blumenau',},
      { id: '2', nome: 'Gaspar'},
      { id: '3', nome: 'Indaial'},
      { id: '4', nome: 'Brusque'}
  ]

  ufs = [
    { id: '1', nome: 'Santa Catarina',},
    { id: '2', nome: 'Paraná'},
    { id: '3', nome: 'Rio grande do Sul'},
  ]

  

}

<cadastro-base [entidade]="entidade">

    <span class="definicaoTituloTela">Cadastro de pessoas</span>
    <span class="definicaoBotoesPersonalizados"></span>
    <span class="definicaoLinksPersonalizados"></span>


    <div class="definicacaoCampos">

      <div class="form-row">
          <div class="form-group col-md-2">
              <label for="id">Id</label>
              <input class="form-control" id="id" disabled="true"  [(ngModel)]="entidade.dados.id"  name="id"/>
          </div>
          <div class="form-group col-md-10 required" > 
              <label for="nome">Nome</label>
              <input class="form-control" id="nome" [(ngModel)]="entidade.dados.nome" placeholder="Nome" name="nome" required/>
          </div>
      </div>      

      <div class="form-row">
          <div class="form-group col-md-10">
              <label for="endereco">Endereço</label>
              <input class="form-control" id="endereco" [(ngModel)]="entidade.dados.endereco" placeholder="Endereço" name="endereco" />
          </div>
          <div class="form-group col-md-2">
              <label for="numero">Número</label>
              <input type="number" class="form-control" id="numero" [(ngModel)]="entidade.dados.numero" placeholder="Número" name="numero">
          </div>
      </div>

      <div class="form-row">
          <div class="form-group col-md-10">
            <label for="bairro">Bairro</label>
            <input class="form-control" id="bairro" [(ngModel)]="entidade.dados.bairro" placeholder="Bairro" name="bairro"/>
          </div>
          <div class="form-group col-md-2">
            <label for="cep">Cep</label>
            <input class="form-control" id="cep" [(ngModel)]="entidade.dados.cep" placeholder="Cep" name="cep"/>
          </div>
      </div>

      <div class="form-row">
          <div class="form-group col-md-6">
            <label for="cidade">Cidade</label>
            <select id="cidade" class="form-control"  [(ngModel)]="entidade.dados.cidade" [ngModelOptions]="{standalone: true}" >
              <option [ngValue]="pais.id" *ngFor="let pais of paises">{{pais.nome}}</option>
            </select>
          </div>

          <div class="form-group col-md-6">
            <label for="uf">Uf</label>
            <select id="uf" class="form-control"  [(ngModel)]="entidade.dados.uf" [ngModelOptions]="{standalone: true}" >
              <option [ngValue]="uf.id" *ngFor="let uf of ufs">{{uf.nome}}</option>
            </select>
          </div>
      </div>   

      <div class="form-row">
          <div class="form-group col-md-4">
            <label for="dataNascimento">Data de nascimento</label>
            <input type="date" class="form-control" id="dataNascimento"  [(ngModel)]="entidade.dados.dataNascimento" placeholder="Data de nascimento"  name="dataNascimento"/>
          </div>
          <div class="form-group col-md-4">
              <label class="form-check-label" for="receberNoticias">Receber notícias</label>
              <div class="form-check">
                <input class="form-check-input" type="checkbox" id="receberNoticias" [(ngModel)]="entidade.dados.receberNoticias" [ngModelOptions]="{standalone: true}">
              </div>  
          </div>

          <div class="form-group col-md-4">
            <label for="uf">Fumante:</label>
            <div class="form-check">
              <input class="form-check-input" type="radio" name="fumante" id="fumanteSim" value="S" [(ngModel)]="entidade.dados.fumante" > 
              <label class="form-check-label" for="fumanteSim">Sim</label>
            </div>
            <div class="form-check">
              <input class="form-check-input" type="radio" name="fumante" id="fumanteNao" value="N" [(ngModel)]="entidade.dados.fumante">
              <label class="form-check-label" for="fumanteNao">Não</label>
            </div>
          </div>
          
      </div>
  </div>

</cadastro-base>

// frontend-react/src/telas/pessoa/CadastroPessoa.js
import React from 'react'
import CadastroBase from '../../componentes/CadastroBase';

export default class CadastroPessoa extends CadastroBase {
   
    
    render() { 

        let dados = this.state.dados;
        
        return (
             <CadastroBase 
                definicaoTituloTela={<span>Cadastro de pessoas</span>}
                definicaoCampos={
                    <div className="definicacaoCampos">
                        <div className="form-row">
                            <div className="form-group col-md-2">
                                <label htmlFor="id">Id</label>
                                <input className="form-control" id="id" disabled={true}  value={dados.id}  name="id"/>
                            </div>
                            <div className="form-group col-md-10 required" > 
                                <label htmlFor="nome">Nome</label>
                                <input className="form-control" id="nome" value={dados.nome} placeholder="Nome" name="nome" required/>
                            </div>
                        </div>
                        <div className="form-row">
                            <div className="form-group col-md-10">
                                <label htmlFor="endereco">Endereço</label>
                                <input className="form-control" id="endereco" value={dados.endereco} placeholder="Endereço" name="endereco" />
                            </div>
                            <div className="form-group col-md-2">
                                <label htmlFor="numero">Número</label>
                                <input type="number" className="form-control" id="numero" value={dados.numero} placeholder="Número" name="numero"/>
                            </div>
                        </div>
                        <div className="form-row">
                            <div className="form-group col-md-10">
                                <label htmlFor="bairro">Bairro</label>
                                <input className="form-control" id="bairro" value={dados.bairro} placeholder="Bairro" name="bairro"/>
                            </div>
                            <div className="form-group col-md-2">
                                <label htmlFor="cep">Cep</label>
                                <input className="form-control" id="cep" value={dados.cep} placeholder="Cep" name="cep"/>
                            </div>
                        </div>



                    </div>    
                }
             >



                 
             </CadastroBase>
        )        
    }            
  
}
