// frontend-vuejs/src/telas/pessoas/Pesquisa.vue
<template v-slot:gridResultado>
  <div id="frmPessoaSel">
      <PesquisaComponent :entidade="entidade" @atualizacao-entidade="atualizaEntidade">

        <template slot="camposFiltro"></template>  

        <template slot="tabelaResultado"> 
          <table  class="table table-hover">
            <thead class="thead-light">
              <tr>
                <th scope="col">Id</th>
                <th scope="col">Nome</th>
                <th scope="col">Endereço</th>
              </tr>
            </thead>
            <tbody>
                <tr v-for="item in entidade.dados" v-bind:key="item.id">
                  <td><a :href="'/' +  entidade.nome  + '/cadastro/' + item.id">{{ item.id }}</a></td>
                  <td>{{ item.nome }}</td>
                  <td>{{enderecoCompleto(item)}}</td>
                </tr>
            </tbody>    
          </table>
        </template>

      </PesquisaComponent>       
  </div>
</template>

<script>
import PesquisaComponent from '../../components/PesquisaComponent.vue'

export default {
  name: 'App',
  components: {
    PesquisaComponent
  },

  data() {
    return {
      entidade: {
        nome: "pessoas",
        dados: [] 
      }
    }  
  },

  methods: {
    atualizaEntidade (dados) {
      this.entidade.dados = dados 
    }
  },

   computed: {
     enderecoCompleto: () => (item) => {
       var endereco = '';
       if  (item.endereco != undefined) endereco = item.endereco;
       if  (item.numero != undefined) endereco = endereco + ', ' + item.numero;
       if  (item.bairro != undefined) endereco = endereco + ' - ' + item.bairro;
       return endereco;
     }

   }  
}
</script>



<style>
</style>

// frontend-angular/src/app/components/pessoa/pesquisa.component.ts
import { Component } from '@angular/core';
import { Entidade } from 'src/app/entidade-model';

@Component({
  selector: 'pessoa-pesquisa',
  templateUrl: './pesquisa.component.html',
})
export class PesquisaComponent {

  entidade: Entidade = new Entidade("pessoas");
  
  
}

<div id="frmPessoaSel">
   <pesquisa-base [entidade]="entidade">
      <div class="tabelaResultado">
        <table  class="table table-hover">
          <thead class="thead-light">
            <tr>
              <th scope="col">Id</th>
              <th scope="col">Nome</th>
              <th scope="col">Endereço</th>
            </tr>
          </thead>
          <tbody>
              <tr *ngFor="let item of entidade.dados; let i = index">
                <td><a [routerLink]="['/',entidade.nome,'cadastro',item.id]">{{item.id}}</a></td>
                <td>{{item.nome}}</td>
                <td>{{item.endereco}}</td>
              </tr>
          </tbody>    
        </table>

      </div>

    
   </pesquisa-base>
  
</div>
