// frontend-angular/src/telas/pessoas/pesquisa.component.ts
import { Component } from '@angular/core';
import { PesquisaComponentBase} from '../../components/pesquisa.component'

@Component({
  selector: 'app-root',
  templateUrl: './pesquisa.component.html',
  //styleUrls: ['./app.component.css']
})
export class PesquisaComponent {
}

<div id="frmPessoaSel">
    <!--<PesquisaComponent :entidade="entidade" @atualizacao-entidade="atualizaEntidade">
      
      <template slot="camposFiltro"></template>  

      <template slot="tabelaResultado"> 
    -->
    <pesquisa-component></pesquisa-component>

        <table  class="table table-hover">
          <thead class="thead-light">
            <tr>
              <th scope="col">Id</th>
              <th scope="col">Nome</th>
              <th scope="col">Endereço</th>
            </tr>
          </thead>
          <tbody>
              <tr v-for="item in entidade.dados" v-bind:key="item.id">
                <td><a>aaa</a></td>
                <td>aaa</td>
                <td>bbb</td>
              </tr>
          </tbody>    
        </table>
      <!--</template>

    </PesquisaComponent>
  -->       
</div>

<script>
// import PesquisaComponent from '../../components/PesquisaComponent.vue'

// export default {
//   name: 'App',
//   components: {
//     PesquisaComponent
//   },

//   data() {
//     return {
//       entidade: {
//         nome: "pessoas",
//         dados: [] 
//       }
//     }  
//   },

//   methods: {
//     atualizaEntidade (dados) {
//       this.entidade.dados = dados 
//     }
//   },

//    computed: {
//      enderecoCompleto: () => (item) => {
//        var endereco = '';
//        if  (item.endereco != undefined) endereco = item.endereco;
//        if  (item.numero != undefined) endereco = endereco + ', ' + item.numero;
//        if  (item.bairro != undefined) endereco = endereco + ' - ' + item.bairro;
//        return endereco;
//      }

//    }  
// }
</script>



<style>
</style>

// frontend-vuejs/src/telas/produtos/Pesquisa.vue
<template v-slot:gridResultado>
  <div id="frmPessoaSel">
      <PesquisaComponent :entidade="entidade" @atualizacao-entidade="atualizaEntidade">

        <template slot="camposFiltro"></template>  

        <template slot="tabelaResultado"> 
          <table  class="table table-hover">
            <thead class="thead-light">
              <tr>
                <th scope="col">Id</th>
                <th scope="col">Nome</th>
                <th scope="col">Preco</th>
                <th scope="col">Quantidade</th>
              </tr>
            </thead>
            <tbody>
                <tr v-for="item in entidade.dados" v-bind:key="item.id">
                  <td><a :href="'/' +  entidade.nome  + '/cadastro/' + item.id">{{ item.id }}</a></td>
                  <td>{{ item.nome }}</td>
                  <td>{{ item.quantidade }}</td>
                  <td>{{ item.preco }}</td>
                </tr>
            </tbody>    
          </table>
        </template>

      </PesquisaComponent>       
  </div>
</template>

<script>
import PesquisaComponent from '../../components/PesquisaComponent.vue'

export default {
  name: 'App',
  components: {
    PesquisaComponent
  },

  data() {
    return {
      entidade: {
        nome: "produtos",
        dados: [] 
      }
    }  
  },

  methods: {
    atualizaEntidade (dados) {
      this.entidade.dados = dados 
    }
  },

}
</script>



<style>
</style>
