// frontend-vuejs/src/components/PesquisaComponent.vue
<template>
  <div class="pesquisa">

    <div class="alert alert-success" role="alert" id="div_mensagens" style="display: none;"/>

    <div id="barraBotoesPesquisa">
      <button type="submit" id="btnPesquisar" class="btn btn-primary" @click="pesquisar">Pesquisar</button>&nbsp;&nbsp;
      <button type="button" id="btnNovo" class="btn btn-primary" @click="novo">Novo</button>&nbsp;&nbsp;
    </div> 
    <br/>

    <slot name="camposFiltro"></slot>
    
    <slot name="tabelaResultado">
        <slot name="cabecalho"></slot>
    </slot>
    
    <nav aria-label="Page navigation example">
      <ul class="pagination justify-content-end">
        <li class="page-item disabled">
          <a class="page-link" href="#" tabindex="-1">Anterior</a>
        </li>
        <li class="page-item"><a class="page-link" href="#">1</a></li>
        <li class="page-item"><a class="page-link" href="#">2</a></li>
        <li class="page-item"><a class="page-link" href="#">3</a></li>
        <li class="page-item">
          <a class="page-link" href="#">Próximo</a>
        </li>
      </ul>
    </nav>




  </div>
</template>

<script>
  import CrudService from "../services/CrudService"
 
  export default {
    name: 'CrudComponent',
    props: {
      entidade: {}
    },

    created() {
        this.CrudService = new CrudService(this.entidade.nome);
    },

    methods: {
      pesquisar: function() {
        this.CrudService.getAll().then(response => {
            this.$emit('atualizacao-entidade',response.data)
        })   
      },

      novo: function() {
        this.$router.push(`/${this.entidade.nome}/cadastro`)
      }
    },

   mounted () {
     this.pesquisar()
   },
    
  }
  


  

</script>



<style scoped>
  #barraBotoesPesquisa {
    text-align: right;
  }
</style>

// frontend-angular/src/components/pesquisa.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'pesquisa-component',
  templateUrl: './pesquisa.component.html',
  //styleUrls: ['./app.component.css']
})
export class PesquisaComponentBase {
}

<div class="pesquisa">

  <div class="alert alert-success" role="alert" id="div_mensagens" style="display: none;"></div>

  <div id="barraBotoesPesquisa">
    <button type="submit" id="btnPesquisar" class="btn btn-primary" click="pesquisar">Pesquisar</button>&nbsp;&nbsp;
    <button type="button" id="btnNovo" class="btn btn-primary" click="novo">Novo</button>&nbsp;&nbsp;
  </div> 
  <br/>

  <slot name="camposFiltro"></slot>
  
  <slot name="tabelaResultado">
      <slot name="cabecalho"></slot>
  </slot>
  
  <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-end">
      <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1">Anterior</a>
      </li>
      <li class="page-item"><a class="page-link" href="#">1</a></li>
      <li class="page-item"><a class="page-link" href="#">2</a></li>
      <li class="page-item"><a class="page-link" href="#">3</a></li>
      <li class="page-item">
        <a class="page-link" href="#">Próximo</a>
      </li>
    </ul>
  </nav>




</div>

<script>
  // import CrudService from "../services/CrudService"
 
  // export default {
  //   name: 'CrudComponent',
  //   props: {
  //     entidade: {}
  //   },

  //   created() {
  //       this.CrudService = new CrudService(this.entidade.nome);
  //   },

  //   methods: {
  //     pesquisar: function() {
  //       this.CrudService.getAll().then(response => {
  //           this.$emit('atualizacao-entidade',response.data)
  //       })   
  //     },

  //     novo: function() {
  //       this.$router.push(`/${this.entidade.nome}/cadastro`)
  //     }
  //   },

  //  mounted () {
  //    this.pesquisar()
  //  },
    
  // }
  


  

</script>



<style scoped>
  #barraBotoesPesquisa {
    text-align: right;
  }
</style>
