// frontend-react/src/componentes/CadastroBase.js
import React, { Component } from 'react'
import CrudService from '../servicos/CrudService';

export default  class CadastroBase extends Component {

  constructor(props) {  
      super(props);  
      this.gravar = this.gravar.bind(this);
      this.novo = this.novo.bind(this);
      this.clonar = this.clonar.bind(this);
      this.novaPesquisa = this.novaPesquisa.bind(this);
      this.excluir = this.excluir.bind(this);

  }; 

  componentWillMount = () => {
    var id = window.location.href.split('/')[window.location.href.split('/').length - 1];
    if  (id) {
        this.editar(id);
    } else {
        this.novo();
    }
  }

  limparMensagem = () => {
    this.setState({   
      mensagemSucesso: "",
      mensagemErro:""
    }); 
  }


  novo = () => {
    console.log("novo");
    this.limparMensagem();
    this.setState({   
      dados : "",
      estadoFormulario: "INSERCAO"
    }); 
  }

  gravar = () => {
    console.log("gravar")
    this.setState({   
      mensagemSucesso : "Registro gravado com sucesso!"
    }); 
  }
  
  editar  = (id) => {
      console.log("editar");
      this.limparMensagem();  
      CrudService.get(id)
        .then(response => {
          console.log(response.data)
          this.setState({   
            dados : response.data,
            estadoFormulario: "EDICAO"
          }); 
        })
        .catch(e => {
          console.log(e);
        });
  };

  clonar = () => {
    console.log("clonar") 
    this.limparMensagem();
    this.setState({   
      estadoFormulario: "INSERCAO",
      mensagemSucesso : "Registro clonado com sucesso!"
    }); 
    
  }

  novaPesquisa = () => {
    console.log("pesquisar") 
  } 

  excluir = () => {
    console.log("excluir") 

    this.novo();
    this.setState({   
      mensagemSucesso : "Registro excluído com sucesso!"
    }); 
  }



  render() {
    console.log("render");
    return (
      <div className="cadastro">
        <form>


          <div id="divMensagens">
            {
              this.state.mensagemSucesso !== '' ? (
                  <div className="alert alert-primary" role="alert" id="div_mensagemSucesso">{this.state.mensagemSucesso}</div>
              ) : ""
            } 
            {
              this.state.mensagemErro !== '' ? (
                <div className="alert alert-danger"  role="alert" id="div_mensagemErro" >{this.state.mensagemErro}</div>
              ) : ""
            } 
          </div>

          <div className="modal fade" id="exampleModal" tabIndex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div className="modal-dialog" role="document">
              <div className="modal-content">
                <div className="modal-header">
                  <h5 className="modal-title" id="exampleModalLabel">Confirmação</h5>
                  <button type="button" className="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div className="modal-body">
                  Confirma a exclusão do registro?
                </div>
                <div className="modal-footer">
                  <button type="button" className="btn btn-secondary" data-dismiss="modal">Não</button>
                  <button type="button" className="btn btn-danger" data-dismiss="modal" onClick={this.excluir}>Sim</button>
                </div>
              </div>
            </div>
          </div>


          <div className="form-row">
            <div className="col-md-4"><p className="h4 text-primary">{this.props.definicaoTituloTela}</p> </div>
            <div className="col-md-8" id="barraBotoesCadastro">
              <button type="button" id="btnGravar" className="btn btn-primary" onClick={this.gravar}>Gravar</button>&nbsp;
              <button type="button" id="btnNovo" className="btn btn-primary" onClick={this.novo}>Novo</button>&nbsp;

              {this.state.estadoFormulario === 'EDICAO' ? (
                 <span><button type="button" id ="btnClonar" className="btn btn-primary" onClick={this.clonar}>Clonar</button>&nbsp;</span>
              ) : "" 
              }

              <button type="button" id="btnNovaPesquisa" className="btn btn-primary" onClick={this.novaPesquisa}>Nova pesquisa</button>&nbsp;

              {this.state.estadoFormulario === 'EDICAO' ? (
                   <span><button type="button" id="btnExcluir" className="btn btn-danger" data-toggle="modal" data-target="#exampleModal"> Excluir</button>&nbsp;</span>
                ) : ""
              }

              {this.props.definicaoBotoesPersonalizados}   
            </div>   
          </div>

          <hr/>

          <div>
              {this.props.definicaoLinksPersonalizados}   
          </div>  
          {this.props.definicaoCampos}   

        </form>

      </div>
    )
  }
}

// frontend-angular/src/app/components/cadastro/cadastro-base.component.ts
import { Component, OnInit, Input, Output } from '@angular/core';
import {ActivatedRoute, Router} from '@angular/router';
import { CrudService } from 'src/app/services/crud.service';
import { Entidade } from 'src/app/model/entidade-model'
import { HttpClient } from '@angular/common/http';


@Component({
  selector: 'cadastro-base',
  templateUrl: './cadastro-base.component.html',
  styles: ['#barraBotoesCadastro {text-align: right;}']
})

export class CadastroBase implements OnInit {

    @Input() 
    @Output()
    entidade: Entidade;

    estadoFormulario: any;
    mensagemErro: any = '';
    mensagemSucesso: any = '';

    crudService: CrudService
    

    constructor(private route: ActivatedRoute, private router: Router, private http: HttpClient) { }

    ngOnInit(): void {
        this.crudService = new CrudService(this.entidade, this.http);
        this.estadoFormulario = "INSERCAO"
        let id = this.route.snapshot.paramMap.get('id');
        if  (id) {
            this.carregarEntidade(id)
        }    
        
    }

    carregarEntidade(id): void {
        this.crudService.get(id).subscribe(
            data => {
                this.entidade.dados = data;
                this.estadoFormulario = "EDICAO"
                this.aposCarregar();
            },
            error => {
                console.log(error);
                if  (error.status = 404) {
                    this.mensagemErro="Registro não encontrado com id: " + id;
                } else {
                    console.log(error);
                    this.mensagemErro="Erro ao carregar registro com id: " + id + ". Erro: " + error.statusText;

                }    
            }
        );

    }

    gravar(): void {
        this.limparMensagem();
        this.antesGravar();
        if  (this.estadoFormulario == "INSERCAO") {
            this.crudService.create(this.entidade.dados).subscribe(
                data => {
                    this.entidade.dados = data;
                    this.estadoFormulario="EDICAO";
                    this.mensagemSucesso = "Registro gravado com sucesso!";
                },
                error => {
                    console.log(error);
                    this.mensagemErro="Erro ao gravar novo registro. Erro: " + error.statusText;
                }
            )
            
        } else {
            this.crudService.update(this.entidade.dados.id, this.entidade.dados).subscribe(
                data => {
                    this.mensagemSucesso = "Registro gravado com sucesso!"
                },
                error => {
                    console.log(error);
                    this.mensagemErro="Erro ao atualizar registro. Erro: " + error.statusText;
                }
            )
        }
        this.aposGravar();
    }

    
    limparMensagem(): void {
        this.mensagemSucesso="";
        this.mensagemErro="";
    }

    novo(): void {
        this.limparMensagem();
        this.estadoFormulario="INSERCAO";
        this.entidade.dados = {};
        this.setarFoco();
        this.aposNovo();
    }
    
    setarFoco(): void {
        document.getElementsByTagName("input")[1].focus();  
    }

    excluir(): void {
        this.limparMensagem();
        this.antesExcluir();
        this.crudService.delete(this.entidade.dados.id).subscribe(
            data => {
                this.novo() 
                this.mensagemSucesso = "Registro excluído com sucesso!";
                this.setarFoco();
            },
            error => {
                console.log(error);
                this.mensagemErro="Erro ao excluir registro. Erro: " + error.statusText;
            }
        )
        this.aposExcluir();
    }
  
    

    clonar(): void {
        this.limparMensagem();
        this.entidade.dados.id = "";
        this.estadoFormulario="INSERCAO"
        this.mensagemSucesso = "Registro clonado com sucesso!";
        this.setarFoco();
        this.aposClonar();
    }
    

    novaPesquisa(): void {
        this.router.navigate([`/${this.entidade.nome}/pesquisa`]);
    }

    // métodos para ser subscritos em seus descendentes
    aposGravar() {}
    antesGravar() {}
    aposExcluir() {}
    antesExcluir() {}
    aposClonar() {}
    aposNovo() {}
    aposCarregar() {}



}



<form ngNativeValidate #form> 

  <div id="divMensagens">
    <div class="alert alert-primary" *ngIf="mensagemSucesso != ''" role="alert" id="div_mensagemSucesso">{{mensagemSucesso}}</div>
    <div class="alert alert-danger" *ngIf="mensagemErro != ''" role="alert" id="div_mensagemErro" >{{mensagemErro}}</div>
  </div>

  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Confirmação</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          Confirma a exclusão do registro?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Não</button>
          <button type="button" class="btn btn-danger" data-dismiss="modal" (click)="excluir()">Sim</button>
        </div>
      </div>
    </div>
  </div>


  <div class="form-row">
    <div class="col-md-2"><p class="h4 text-primary"><ng-content select=".definicaoTituloTela"></ng-content></p> </div>
    <div class="col-md-10" id="barraBotoesCadastro" style="text-align: right; ">
      <button type="submit" id="btnGravar" class="btn btn-primary" (click)="form.checkValidity()? gravar() : null">Gravar</button>&nbsp;
      <button type="button" id="btnNovo" class="btn btn-primary" (click)="novo()">Novo</button>&nbsp;
      <button type="button" id ="btnClonar" [hidden]="estadoFormulario != 'EDICAO'" class="btn btn-primary" (click)="clonar()">Clonar</button>&nbsp;
      <button type="button" id="btnNovaPesquisa" class="btn btn-primary" (click)="novaPesquisa()">Nova pesquisa</button>&nbsp;
      <button type="button" id="btnExcluir" [hidden]="estadoFormulario != 'EDICAO'" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal"> Excluir</button>&nbsp;
      <ng-content select=".definicaoBotoesPersonalizados"></ng-content>
    </div>   
  </div>

  <hr/>

  <div>
    <ng-content select=".definicaoLinksPersonalizados"></ng-content>
  </div>



  <div>
    <ng-content select=".definicacaoCampos"></ng-content>
  </div>

</form>
